remote_theme: "mmistakes/minimal-mistakes@4.20.1"
markdown: kramdown
usemathjax: true
include: ["_include", "_layouts"]
plugins:
  - jekyll-include-cache
  - jekull-feed
  
author:
  name: "Your name"
  avatar: "my_avatar.png"
  bio: "PhD Student in statistics" # Note: Markdown is allowed
  location: "Montpellier, France"
  email            : "myemal@domain.fr"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "?????"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : #"tanguy_lef"
  lastfm           :
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # maybe...
  links:
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/"
